### ISSUE TITLE
框架VCLibs无法安装，导致本软件无法安装

### ISSUE THREAD

**Issue by Rhuua** [xiaoyaocz/biliuwp-lite#104]
我尝试安装本软件包4.3.5及以后的版本，但总是安装错误，提示框架不匹配。
![image](https://user-images.githubusercontent.com/86452502/158308483-ab3bbef1-7404-4a2d-b3c0-096dbcec8db5.png)
然后我尝试安装作者提供的appx安装包，提示因为资源正在使用中，无法安装。
![image](https://user-images.githubusercontent.com/86452502/158308578-e4dea474-62bf-4c76-adcd-ec748015603c.png)
我尝试在任务管理器关闭占用的进程，但无果。网上有用的信息也不多。
唯一有一个微软官方问答中提到可以安装exe版框架。
![image](https://user-images.githubusercontent.com/86452502/158308729-a86cb014-3f52-4b4c-b2d5-17dca150f3e3.png)
但安装后没有改善。
尝试过在安全模式安装，但安全模式无法安装appx；
尝试过用dism++在恢复模式下删除旧框架，但失败；
尝试过更新系统到win10的最新版，但框架没有跟着更新。
现在还是只能用4.3.2版本，每次进入都提示更新，但又不是我不想更……
请问还有什么解决方案？

**Comment by TPAXcc** [comment]
搜一下 Windows Server 装微软商店的教程，然后把里面所有对应包全都安装一下 (就是装微软商店的步骤) 试试

**Comment by Rhuua** [comment]
> 搜一下 Windows Server 装微软商店的教程，然后把里面所有对应包全都安装一下 (就是装微软商店的步骤) 试试

感谢指点！之前看到报错以为单是一个包的问题，按你说的一次更新了三个包，果然成功了！
![image](https://user-images.githubusercontent.com/86452502/158593886-5eda209f-5862-435f-a1f2-e533b0aab4fa.png)
