### ISSUE TITLE
VClib 版本问题

### ISSUE THREAD

**Issue by CNwuyueyu** [xiaoyaocz/biliuwp-lite#120]
win10在官网能下载的最新VClib是14.0.30035，而安装4.3.5以上版本的UWP需要最低VClib是14.0.3070，架构包里提供的也是低版本的VClib，故无法安装4.3.5以上的本软件。

**Comment by xiaoyaocz** [comment]
到此处下载新的框架包 https://xiaoyaocz.lanzouh.com/icZQo0267w0d

**Comment by CNwuyueyu** [comment]
> 到此处下载新的框架包 https://xiaoyaocz.lanzouh.com/icZQo0267w0d

感谢更新架构包，最新版本已经安装成功
