### ISSUE TITLE
[已解决]见描述

### ISSUE THREAD

**Issue by TPAXcc** [xiaoyaocz/biliuwp-lite#121]
在 部分视频 拖动 视频进度条 时经常会出现 [未指定的错误 0x] (似乎只有部分视频会出现此 BUG, 开发者可尝试使用 P1 中的视频 BV 复现)
在打开 [视频自动加载] 后 关闭标签页 会导致 音频在后台播放 (即没有标签页 但还有声音)
 ![P1](https://s1.328888.xyz/2022/03/28/J4ivS.jpg)

**Comment by TPAXcc** [comment]
> 在 部分视频 拖动 视频进度条 时经常会出现 [未指定的错误 0x] (似乎只有部分视频会出现此 BUG, 开发者可尝试使用 P1 中的视频 BV 复现)
![Uploading 20220328_000137_HDR.jpg…]()

在打开 [视频自动加载] 后 关闭标签页 会导致 音频在后台播放 (即没有标签页 但还有声音)

**Comment by TPAXcc** [comment]
> 在 部分视频 拖动 视频进度条 时经常会出现 [未指定的错误 0x] (似乎只有部分视频会出现此 BUG, 开发者可尝试使用 P1 中的视频 BV 复现) 
在打开 [视频自动加载] 后 关闭标签页 会导致 音频在后台播放 (即没有标签页 但还有声音)

**Comment by TPAXcc** [comment]
> 在 部分视频 拖动 视频进度条 时经常会出现 [未指定的错误 0x] (似乎只有部分视频会出现此 BUG, 开发者可尝试使用 P1 中的视频 BV 复现) 在打开 [视频自动加载] 后 关闭标签页 会导致 音频在后台播放 (即没有标签页 但还有声音)



> 在 部分视频 拖动 视频进度条 时经常会出现 [未指定的错误 0x] (似乎只有部分视频会出现此 BUG, 开发者可尝试使用 P1 中的视频 BV 复现) 在打开 [视频自动加载] 后 关闭标签页 会导致 音频在后台播放 (即没有标签页 但还有声音)

![Uploading 20220328_000137_HDR.jpg…]()

**Comment by TPAXcc** [comment]
![Uploading 20220328_000137_HDR.jpg…]()

**Comment by TPAXcc** [comment]
https://s1.328888.xyz/2022/03/28/J4ivS.jpg

**Comment by TPAXcc** [comment]
md我人麻了开发者自己看吧应该能用

**Comment by TPAXcc** [comment]
破案了，原因是因为默认使用 NVIDIA 独显做为输出核心，导致 HEVC 出现问题，在 NVIDIA 控制面板 中将输出核心设置为 集成显示 就可以了，建议开发者再帮助中添加此项

**Comment by TPAXcc** [comment]
请开发者查看此 issues 后 关闭此 issues。

**Comment by xiaoyaocz** [comment]
收到，谢谢
