### ISSUE TITLE
希望还是能在微软商店更新最新版

### ISSUE THREAD

**Issue by staoran** [xiaoyaocz/biliuwp-lite#126]
虽然商店搜不到，但是可以通过 `ms-windows-store://pdp/?productid=9n7c87236453` 进入详情页安装，会方便很多。所以还是希望能上传微软商店或更新最新版。

**Comment by misaka10843** [comment]
可能为什么微软商店搜不到就是因为b站封杀了吧（毕竟都可以缓存番剧）
再上架可能也会被投诉下架
所以还是好好的在GitHub下吧🤣

**Comment by staoran** [comment]
我觉得搜不到更好更安全吧，只是现在发现一种偷渡的方式就是浏览器通过URL进入，所以如果能把 哔哩哔哩UWP(第三方) 更新成最新版就完美了，我们就可以通过微软商店安装或更新了
![image](https://user-images.githubusercontent.com/7844538/161875062-20413da6-ef6b-409c-a882-36d8435aaeec.png)

**Comment by jkqxl** [comment]
@staoran 
这是两个不同的版本，你图片上的是旧版，因为投诉而不可能再更新了

本Github是使用的新的测试版，不是同一个软件
