### ISSUE TITLE
请求增加一个的功能开关，打开网页可以直接调用浏览器

### ISSUE THREAD

**Issue by jkqxl** [xiaoyaocz/biliuwp-lite#136]
希望可以在播放界面右侧的简介里，或者评论区打开的网页、网盘链接，可以直接调用浏览器打开，而不是先在软件打开，之后手动调用浏览器

在软件打开，没有浏览器速度快，下载东西也不是很方便

**Comment by xiaoyaocz** [comment]
4.4.1已解决
