### ISSUE TITLE
WIN11证书问题无法安装

### ISSUE THREAD

**Issue by Linglegl** [xiaoyaocz/biliuwp-lite#158]
：） 此应用包未使用受信任的证书签名。请与系统管理员或应用程序开发人员联系，以获取新证书或带有受信任证书的应用程序包。应用程序包中签名的根证书和所有即时证书必须受信任（0x800B010A）

**Comment by lzy3240** [comment]
此应用包未使用受信任的证书签名。请与系统管理员或应用程序开发人员联系，以获取新证书或带有受信任证书的应用程序包。应用程序包中签名的根证书和所有即时证书必须受信任（0x800B010A）

**Comment by xiaoyaocz** [comment]
你好，请确定证书安装至

**Comment by chuanzz** [comment]
同样的问题，研究了很久，试一下这样：
在证书的目录执行以下命令
`certutil.exe -addstore TrustedPeople .\BiliLite.UWP_4.3.10.0_x64.cer`
然后就能正常安装应用了。
我怀疑是最新版本的系统自动安装证书的过程出了什么问题，才导致这样。
