### ISSUE TITLE
点击动态图片后闪退，日志也记录不下来，

### ISSUE THREAD

**Issue by RYX-3212103383** [xiaoyaocz/biliuwp-lite#165]
UWP
版本：4.3.10和4.4.0
系统
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎11/‎11
操作系统内部版本	19044.1706
体验	Windows Feature Experience Pack 120.2212.4170.0

https://user-images.githubusercontent.com/55491921/172042659-354aea4e-9322-40bc-b91d-b7feee32c7c2.mp4

**Comment by xiaoyaocz** [comment]
合并 #195
