### ISSUE TITLE
右侧视频详情宽度调整后普通视频和番剧不一致

### ISSUE THREAD

**Issue by lucifere02** [xiaoyaocz/biliuwp-lite#166]
如下图所示，调整宽度后打开一个视频和打开番剧，右侧宽度差异较大，有点难受，希望可以优化，谢谢开发者！
![image](https://user-images.githubusercontent.com/86308431/172054594-cfbb8642-9a4c-40b9-8d83-7fb3bbbe20cd.png)
![image](https://user-images.githubusercontent.com/86308431/172054853-be7d669d-5b76-4049-a4d5-7934d79a130a.png)
![image](https://user-images.githubusercontent.com/86308431/172054857-112dc612-74e5-4d51-bb6d-704803e788d8.png)

**Comment by xiaoyaocz** [comment]
4.4.1已修复

**Comment by lucifere02** [comment]
> 4.4.1已修复

感谢开发者！
