### ISSUE TITLE
视频只有1P时列表循环失效

### ISSUE THREAD

**Issue by lucifere02** [xiaoyaocz/biliuwp-lite#167]
当视频只有1P时，列表循环无效，依然是播放完一遍后自动暂停。如果切换成单集循环又会导致看多P视频时不方便。
![image](https://user-images.githubusercontent.com/86308431/172055513-e63960fc-989c-486f-b2f0-d1478638cf70.png)

**Comment by xiaoyaocz** [comment]
4.4.1已修复

**Comment by lucifere02** [comment]
> 4.4.1已修复

感谢开发者！
