### ISSUE TITLE
Windows Defender 从4.4.0_x64压缩包中检出Trojan:Script/Oneeva.A!ml

### ISSUE THREAD

**Issue by citratecycle** [xiaoyaocz/biliuwp-lite#176]
![image](https://user-images.githubusercontent.com/48681002/173329947-4a67438a-07c9-42ec-9742-6dbe1490f989.png)

是否符合预期？

**Comment by xiaoyaocz** [comment]
由于程序包中内置了win32应用(用于转码导出视频)，所以Windows Defender可能会误报
