### ISSUE TITLE
视频亮度低，不正常

### ISSUE THREAD

**Issue by Myleswork** [xiaoyaocz/biliuwp-lite#181]
![5IMTNBT3R285A8N_H4`6N{4](https://user-images.githubusercontent.com/60376065/174271786-feeef677-9073-4c5c-b9ec-8d15688f6b66.png)
版本：4.3.10.0 ；4.4.0.0（上一个版本也有这个问题）
win10家庭版 19044.1706
大会员，已登录
所有视频输出格式均有此问题，弹幕和内容播放均正常

问题：视频很暗

**Comment by xiaoyaocz** [comment]
4.4.1已解决
