### ISSUE TITLE
【BUG】关于字幕问题反馈

### ISSUE THREAD

**Issue by Wiauy** [xiaoyaocz/biliuwp-lite#186]
**图片示例如下，已开启繁体字幕转简体，但部分字依旧显示繁体字，例如第二张图的"为什么"三个字就还是繁体，望修复！**
_Ver 4.4.0.0 x64
Windows 10 专业版 x64 版本：19044
大会员：是 登录状态：已登录_
![问题](https://user-images.githubusercontent.com/108172114/175763464-915065fe-f53e-4f97-af44-0162e7aba8ef.jpg)
![问题2](https://user-images.githubusercontent.com/108172114/175763470-b37da62d-766e-4be0-aac8-8873a89fad2f.jpg)

**Comment by Wiauy** [comment]
**若无法修复，建议增加净化替换字幕字样规则，顺便让字幕字体可自由替换**
_目前发现还有“于”、“干"繁体未转换简体_

**Comment by xiaoyaocz** [comment]
4.4.1已解决
