### ISSUE TITLE
证书问题，安装不了

### ISSUE THREAD

**Issue by six220mao** [xiaoyaocz/biliuwp-lite#197]
已经把证书安装到 受信任 里面了，还是报错下面这个

[此应用包未使用受信任的证书签名。请与系统管理员或应用程序开发人员联系，以获取新证书或带有受信任证书的应用程序包。应用程序包中签名的根证书和所有即时证书必须受信任（0x800B010A） 

![证书](https://user-images.githubusercontent.com/30646601/179002345-263f9555-04a9-4145-bdda-32c2fe65378e.png)
![安装](https://user-images.githubusercontent.com/30646601/179002365-340a4b83-3152-40ed-be5f-b67c328607bc.png)

**Comment by paditianxiu** [comment]
我也是咋办
PS C:\Users\Administrator> Add-AppxPackage -Path D:\桌面\BiliLite.UWP_4.4.1.0_x64\BiliLite.Packages_4.4.1.0_x64.msix    Add-AppxPackage : 部署失败，原因是 HRESULT: 0x800B0109, 已处理证书链，但是在不受信任提供程序信任的根证书中终止。
错误 0x800B0109: 应用包或捆绑包中的签名的根证书必须是受信任的证书。

**Comment by six220mao** [comment]
我用PowerShell也提醒这个，不知道怎么搞

**Comment by six220mao** [comment]
> 我也是咋办 PS C:\Users\Administrator> Add-AppxPackage -Path D:\桌面\BiliLite.UWP_4.4.1.0_x64\BiliLite.Packages_4.4.1.0_x64.msix Add-AppxPackage : 部署失败，原因是 HRESULT: 0x800B0109, 已处理证书链，但是在不受信任提供程序信任的根证书中终止。 错误 0x800B0109: 应用包或捆绑包中的签名的根证书必须是受信任的证书。

我用PowerShell命令安装也提醒这个，不知道怎么搞

**Comment by a08078421** [comment]
https://b.nsapps.cn/#/安装证书失败的，请看图安装

**Comment by xiaoyaocz** [comment]
请参考#158
