### ISSUE TITLE
提一个非常非常小的建议

### ISSUE THREAD

**Issue by Thomitics** [xiaoyaocz/biliuwp-lite#2]
建议能自定义新标签页的背景图片![emotion](https://cdn.jsdelivr.net/gh/imaegoo/emotion/bilibili/1f0b87f731a671079842116e0991c91c2c88645a.png)

**Comment by xiaoyaocz** [comment]
已实现

**Comment by Thomitics** [comment]
> 已实现

现在是不是又不能改了 /wul
