### ISSUE TITLE
4.2.0.0版本直播无法播放，调用bvc-play-url-one出错

### ISSUE THREAD

**Issue by truthlive** [xiaoyaocz/biliuwp-lite#20]
点开直播后黑屏没有画面，弹幕可以正常载入：

![image](https://user-images.githubusercontent.com/25575959/116266803-d270ef80-a749-11eb-85d7-d50f932a7f50.png)

![image](https://user-images.githubusercontent.com/25575959/116267030-08ae6f00-a74a-11eb-806a-54863bd90b07.png)

**Comment by xiaoyaocz** [comment]
无法重现此问题，可能B站服务器偶尔抽风

**Comment by truthlive** [comment]
我是在海外看b站，更新了最新的4.2.3之后还是有同样的问题。但发现开了回国的VPN之后可以加载直播不会报错，然而连接非常不稳定，经常断线。不开VPN的时候直接在浏览器上看直播没有这样的问题，请问会不会是海外观看b站直播有单独的api？

**Comment by xiaoyaocz** [comment]
我尝试切换多国VPN打开直播，播放都是正常的。
直播播放地址调用的是网页的API，你尝试下哔哩哔哩网页版能不能打开观看。

**Comment by truthlive** [comment]
找到问题了。。。不知道为啥win10自动把网络代理的选项打开了，关掉就能看直播了，非常感谢！
