### ISSUE TITLE
有条动态不显示

### ISSUE THREAD

**Issue by SIQI0701** [xiaoyaocz/biliuwp-lite#212]
动态加载失败:
{"desc":{"user_profile":{"decorate_card":{"id":32256,"name":"EveOneCat2粉丝","big_card_url":"https://i0.hdslb.com/bfs/garb/item/678cd968bf0a543688bfd292a803af7fc759c1d8.png","jump_url":"https://www.bilibili.com/h5/mall/fans/recommend/32296?navhide=1&mid=12939237&from=dynamic&isdiy=0","card_url":"https://i0.hdslb.com/bfs/garb/item/678cd968bf0a543688bfd292a803af7fc759c1d8.png","card_type":2,"fan":{"is_fan":1,"number":84725,"color":"#f35543","num_desc":"084725"}},"info":{"uid":12939237,"uname":"有棵里里","face":"https://i0.hdslb.com/bfs/face/be058ce1aa77aea9545b7665afb5f1eb83371c25.jpg"},"card":{"official_verify":{"type":0,"desc":"bilibili直播高能主播"}},"vip":{"vipType":2,"vipDueDate":1726848000000,"dueRemark":null,"accessStatus":0,"vipStatus":1,"vipStatusWarn":null,"themeType":0},"pendant":{"pid":0,"name":"","image":"","expire":0,"image_enhance":""},"rank":"10000","sign":"粉丝群583248989 ","level_info":{"current_level":6,"current_min":0,"current_exp":0,"next_exp":null}},"uid":12939237,"type":1,"rid":"698007145790046210","dynamic_id_str":"698007145784803332","dynamic_id":"698007145784803332","rid_str":"698007145790046210","r_type":0,"bvid":null,"view":568,"repost":1,"comment":17,"like":74,"is_liked":0,"timestamp":1661355853,"pre_dy_id":"698004706244427817","orig_dy_id":"698004706244427817","orig_type":8,"uid_type":1,"status":1},"extend_json":"{\"from\":{\"from\":\"ugc_detail\",\"verify\":{\"aegis_enable\":true,\"asw\":{},\"cc\":{},\"csw\":{},\"dc\":{},\"gc\":{},\"need_verify\":true,\"ra\":{},\"sp\":{},\"sw\":{},\"ur\":{}}},\"like_icon\":{\"action\":\"\",\"action_url\":\"\",\"end\":\"\",\"end_url\":\"\",\"start\":\"\",\"start_url\":\"\"}}","card":"{ \"user\": { \"uid\": 12939237, \"uname\": \"有棵里里\", \"face\": \"https:\\/\\/i0.hdslb.com\\/bfs\\/face\\/be058ce1aa77aea9545b7665afb5f1eb83371c25.jpg\" }, \"item\": { \"rp_id\": 698007145790046210, \"uid\": 12939237, \"content\": \"好可爱的封面！关注里棵生抚育中心汪汪！\", \"ctrl\": \"\", \"orig_dy_id\": 698004706244427817, \"pre_dy_id\": 698004706244427817, \"timestamp\": 0, \"reply\": 17, \"orig_type\": 8 }, \"origin\": \"{\\\"aid\\\":387342397,\\\"attribute\\\":0,\\\"attribute_v2\\\":65536,\\\"cid\\\":813444639,\\\"copyright\\\":1,\\\"ctime\\\":1661355285,\\\"desc\\\":\\\"来自8月24日直播\\\\n【有棵里里】\\\\n个人主页：https:\\\\\\/\\\\\\/space.bilibili.com\\\\\\/12939237\\\\n直播间：https:\\\\\\/\\\\\\/live.bilibili.com\\\\\\/264788\\\\n-------------------------------------------------\\\\n剪辑：AGoo\\\\n时轴：AGoo\\\\n封面：AGoo\\\\n后期：AGoo\\\",\\\"dimension\\\":{\\\"height\\\":1080,\\\"rotate\\\":0,\\\"width\\\":1920},\\\"duration\\\":254,\\\"dynamic\\\":\\\"\\\",\\\"first_frame\\\":\\\"https:\\\\\\/\\\\\\/i1.hdslb.com\\\\\\/bfs\\\\\\/storyff\\\\\\/n220824qn25azdo1816qk23f0l3xfa7c_firsti.jpg\\\",\\\"jump_url\\\":\\\"bilibili:\\\\\\/\\\\\\/video\\\\\\/387342397\\\\\\/?page=1&player_preload=null&player_width=1920&player_height=1080&player_rotate=0\\\",\\\"mission_id\\\":853437,\\\"owner\\\":{\\\"face\\\":\\\"https:\\\\\\/\\\\\\/i1.hdslb.com\\\\\\/bfs\\\\\\/face\\\\\\/7bf9c36cd01b8082229770140d6c2fbfc05ab752.jpg\\\",\\\"mid\\\":3461566905190642,\\\"name\\\":\\\"里棵生抚育中心\\\"},\\\"pic\\\":\\\"https:\\\\\\/\\\\\\/i0.hdslb.com\\\\\\/bfs\\\\\\/archive\\\\\\/ef3e9c5746365b8cfc82250ed4241e4b9d056d5a.jpg\\\",\\\"player_info\\\":null,\\\"pub_location\\\":\\\"浙江\\\",\\\"pubdate\\\":1661355285,\\\"rights\\\":{\\\"arc_pay\\\":0,\\\"autoplay\\\":1,\\\"bp\\\":0,\\\"download\\\":0,\\\"elec\\\":0,\\\"hd5\\\":1,\\\"is_cooperation\\\":0,\\\"movie\\\":0,\\\"no_background\\\":0,\\\"no_reprint\\\":1,\\\"pay\\\":0,\\\"pay_free_watch\\\":0,\\\"ugc_pay\\\":0,\\\"ugc_pay_preview\\\":0},\\\"short_link\\\":\\\"https:\\\\\\/\\\\\\/b23.tv\\\\\\/BV1Jd4y1d71E\\\",\\\"short_link_v2\\\":\\\"https:\\\\\\/\\\\\\/b23.tv\\\\\\/BV1Jd4y1d71E\\\",\\\"stat\\\":{\\\"aid\\\":387342397,\\\"coin\\\":4,\\\"danmaku\\\":1,\\\"dislike\\\":0,\\\"favorite\\\":7,\\\"his_rank\\\":0,\\\"like\\\":25,\\\"now_rank\\\":0,\\\"reply\\\":4,\\\"share\\\":1,\\\"view\\\":118},\\\"state\\\":0,\\\"tid\\\":27,\\\"title\\\":\\\"【有棵里里】当场破防！底层小v被观众要求闭嘴\\\",\\\"tname\\\":\\\"综合\\\",\\\"videos\\\":1}\", \"origin_extend_json\": \"{\\\"like_icon\\\":{\\\"action\\\":\\\"\\\",\\\"action_url\\\":\\\"\\\",\\\"end\\\":\\\"\\\",\\\"end_url\\\":\\\"\\\",\\\"start\\\":\\\"\\\",\\\"start_url\\\":\\\"\\\"},\\\"topic\\\":{\\\"is_attach_topic\\\":1}}\", \"origin_user\": { \"info\": { \"uid\": 3461566905190642, \"uname\": \"里棵生抚育中心\", \"face\": \"https:\\/\\/i1.hdslb.com\\/bfs\\/face\\/7bf9c36cd01b8082229770140d6c2fbfc05ab752.jpg\", \"face_nft\": 0 }, \"card\": { \"official_verify\": { \"type\": -1, \"desc\": \"\" } }, \"vip\": { \"vipType\": 0, \"vipDueDate\": 0, \"vipStatus\": 0, \"themeType\": 0, \"label\": { \"path\": \"\", \"text\": \"\", \"label_theme\": \"\", \"text_color\": \"\", \"bg_style\": 0, \"bg_color\": \"\", \"border_color\": \"\" }, \"avatar_subscript\": 0, \"nickname_color\": \"\", \"role\": 0, \"avatar_subscript_url\": \"\" }, \"pendant\": { \"pid\": 0, \"name\": \"\", \"image\": \"\", \"expire\": 0, \"image_enhance\": \"\", \"image_enhance_frame\": \"\" }, \"rank\": \"10000\", \"sign\": \"\", \"level_info\": { \"current_level\": 2 } } }","display":{"origin":{"origin":null,"emoji_info":null,"topic_info":{"emoji_details":null}},"emoji_info":null,"topic_info":null}}

**Comment by xiaoyaocz** [comment]
请更新至4.4.6
