### ISSUE TITLE
无法获取播放地址

### ISSUE THREAD

**Issue by julynet** [xiaoyaocz/biliuwp-lite#215]
ver:4.4.5.0_x64
现象：无法获取播放地址 无代理 4.4.1.0 可用 更新完就不行了
截图：
![image](https://user-images.githubusercontent.com/93466263/187072494-aed3f429-0a30-41ec-94b8-344b3d1454ff.png)

**Comment by xiaoyaocz** [comment]
更新4.4.6

**Comment by julynet** [comment]
> 更新4.4.6

https://b23.wtf/BV1na411R7f3
此视频1080p无法播放（其他分辨率可以） 我主页随机测试 结果相同 但是少部分视频可以正常播放
= =

**Comment by julynet** [comment]
> > 更新4.4.6
> 
> https://b23.tv/BV1na411R7f3 此视频1080p无法播放（其他分辨率可以） 我主页随机测试 结果相同  = =

**Comment by 1376367262** [comment]
高于720P的都是提示无法读取播放地址

**Comment by xraynet** [comment]
同 已更新4.4.6 720p可以 1080提示无法读取播放地址

**Comment by xiaoyaocz** [comment]
已定位问题，晚点再发个版本😂

**Comment by 1376367262** [comment]
> 已定位问题，晚点再发个版本😂

麻烦大佬了(●'◡'●)

**Comment by xiaoyaocz** [comment]
更新至4.4.7
