### ISSUE TITLE
代理服务器可以开关

### ISSUE THREAD

**Issue by 2mysteries** [xiaoyaocz/biliuwp-lite#217]
你好，我建议可以开关代理服务器，可以通过本地的代理来选择片源。忘采纳

**Comment by xiaoyaocz** [comment]
默认请求是不通过服务器代理的，只有获取不到播放链接时才会使用服务器代理。
UWP默认是不能访问本地代理的，可以参考此文章解除限制 https://zhuanlan.zhihu.com/p/363912808

**Comment by 2mysteries** [comment]
把uwp本地代理解除后，那可以用本地代理选择视频源码

**Comment by xiaoyaocz** [comment]
解除后如果开启了本地代理，就会用本地代理去请求

**Comment by 2mysteries** [comment]
好的，谢谢🍊
