### ISSUE TITLE
大佬们好 我尝试在1709版win10下安装最新的 出错

### ISSUE THREAD

**Issue by XieYuDeGitHub** [xiaoyaocz/biliuwp-lite#26]
![image](https://user-images.githubusercontent.com/65640243/118856935-1189ff00-b90a-11eb-822e-1c2d2dc542e6.png)
请问该如何解决呢 是更新window通用平台吗 （本人没怎么接触uwp）

**Comment by xiaoyaocz** [comment]
更新系统

**Comment by XieYuDeGitHub** [comment]
> 更新系统

能不更新系统吗 这精简系统没法更新 能在不更新的情况下安装吗

**Comment by XieYuDeGitHub** [comment]
> 更新系统

我已经更新了 离线框架包的链接已经没了 能给我新的链接吗

**Comment by XieYuDeGitHub** [comment]
> > 更新系统
> 
> 我已经更新了 离线框架包的链接已经没了 能给我新的链接吗

![image](https://user-images.githubusercontent.com/65640243/118913348-de705b80-b95b-11eb-9a0f-108977e8ad08.png)

**Comment by xiaoyaocz** [comment]
https://xiaoyaocz.lanzous.com/iHTink6saih

**Comment by XieYuDeGitHub** [comment]
> https://xiaoyaocz.lanzous.com/iHTink6saih

网页无法打开 尝试使用 114.114.114.114 dns也无法打开
![image](https://user-images.githubusercontent.com/65640243/118917942-8558f580-b964-11eb-963e-78d42236c9ba.png)

**Comment by xiaoyaocz** [comment]
https://xiaoyaocz.lanzoux.com/iHTink6saih

**Comment by XieYuDeGitHub** [comment]
> https://xiaoyaocz.lanzoux.com/iHTink6saih

谢谢

**Comment by XieYuDeGitHub** [comment]
> https://xiaoyaocz.lanzoux.com/iHTink6saih

我应该安装哪一个呢？还是全部安装
![image](https://user-images.githubusercontent.com/65640243/118918465-52633180-b965-11eb-9c42-c35e8a742c3b.png)

**Comment by XieYuDeGitHub** [comment]
> > https://xiaoyaocz.lanzoux.com/iHTink6saih
> 
> 我应该安装哪一个呢？还是全部安装
> ![image](https://user-images.githubusercontent.com/65640243/118918465-52633180-b965-11eb-9c42-c35e8a742c3b.png)

找到答案了

**Comment by XieYuDeGitHub** [comment]
> > > https://xiaoyaocz.lanzoux.com/iHTink6saih
> > 
> > 
> > 我应该安装哪一个呢？还是全部安装
> > ![image](https://user-images.githubusercontent.com/65640243/118918465-52633180-b965-11eb-9c42-c35e8a742c3b.png)
> 
> 找到答案了

安装成功 谢谢大佬
