### ISSUE TITLE
请问大佬有没有SYEngine的VSIX包？

### ISSUE THREAD

**Issue by sancsjohnny** [xiaoyaocz/biliuwp-lite#28]
很喜欢大佬的作品，在努力学习中。
最近发现amamiya的SYEngine已经完全404了，
页面提供的VSIX包也无法下载了，
我尝试在全网找，也没有找到。
看到大佬之前的BilibiliUWP曾经用过SYEngine，
所以想问下大佬，有没有SYEngine的VSIX插件
谢谢大佬

**Comment by xiaoyaocz** [comment]
建议直接使用Nuget包：https://www.nuget.org/packages/SYEngine.uwp/

**Comment by sancsjohnny** [comment]
> 建议直接使用Nuget包：https://www.nuget.org/packages/SYEngine.uwp/

谢大佬指点，问题解决了！
