### ISSUE TITLE
视频无法观看

### ISSUE THREAD

**Issue by XieYuDeGitHub** [xiaoyaocz/biliuwp-lite#30]
截图
![image](https://user-images.githubusercontent.com/65640243/120772552-01516100-c553-11eb-9d72-c8069a479692.png)
好像只有视频无法观看，其余都正常

biliuwp版本4.3.0.0
系统版本 
![image](https://user-images.githubusercontent.com/65640243/120772753-378ee080-c553-11eb-8450-766eec1ec8f2.png)
昨天还能正常的看视频，今天就不行了

**Comment by XieYuDeGitHub** [comment]
[log.txt](https://github.com/xiaoyaocz/biliuwp-lite/files/6597016/log.txt)
日志文件

**Comment by ViperBling** [comment]
同样的问题，上午还行，下午就不行了
![image](https://user-images.githubusercontent.com/17715149/120776771-2647d300-c557-11eb-8099-85dc0dc8ac7c.png)
日志文件：
[20210604.log](https://github.com/xiaoyaocz/biliuwp-lite/files/6597172/20210604.log)

**Comment by citratecycle** [comment]
同样的问题 代码412

**Comment by asky88** [comment]
同样的问题 代码412 会不会是b站服务器升级了？

**Comment by xiaoyaocz** [comment]
更新4.3.1

**Comment by XieYuDeGitHub** [comment]
> 更新4.3.1

弄好了 谢谢
