### ISSUE TITLE
surface proX 安装arm64版本，运行闪退...

### ISSUE THREAD

**Issue by R0yl** [xiaoyaocz/biliuwp-lite#4]
win10（21301.1010）on arm，安装了arm64的版本，支持包也安装了，运行就闪退...

**Comment by Loaker-B** [comment]
我用的4.1.4版本还能用，4.1.6版本包有问题。。。但自己打包也解决不了

**Comment by zhzy0077** [comment]
**先用ARM版吧。**
稍微debug看了下，很多的依赖都没有ARM64的dll，看了下NSDanmaku这种加起来可能不麻烦，https://github.com/yunfandev/SYEngine.uwp 这种依赖多的就可能麻烦得多，甚至要静态编译一个ffmpeg的lib但是这里的ffmpeg都不知道是什么版本，看上去也没人维护了，就挺麻烦。
**总之先用ARM版吧。**

**Comment by zhzy0077** [comment]
又仔细看了一遍 SYEngine 好像也不是什么必要的依赖
等这两个 PR 合并之后再分别发个新版本应该就行了：
https://github.com/xiaoyaocz/NSDanmaku/pull/6
https://github.com/xiaoyaocz/biliuwp-lite/pull/13

但是对于 FLV 的支持可能会有问题，不过现在 bilibili 上也没多少flv的视频了

**Comment by zhzy0077** [comment]
@R0yl  @Loaker-B 
https://github.com/zhzy0077/biliuwp-lite/releases/tag/ARM64 可以试下这个 release 要是遇到什么问题的话ping下我，目前我试着大多数视频都能看了 或者可以merge了 https://github.com/xiaoyaocz/biliuwp-lite/pull/16 后手动打包

**Comment by R0yl** [comment]
surface pro X 测试ARM64可用，很赞，感谢开发者！！
