### ISSUE TITLE
BUG:首页推荐有部分视频无法打开

### ISSUE THREAD

**Issue by tikko-now** [xiaoyaocz/biliuwp-lite#71]
首页的推荐视频，有一些无法被打开

**Comment by tikko-now** [comment]
经过反复尝试，似乎是打开软件后第一个点击的推荐视频无法被打开，之后被点击的视频就会正常

**Comment by 2314933036** [comment]
> 经过反复尝试，似乎是打开软件后第一个点击的推荐视频无法被打开，之后被点击的视频就会正常

不对,往下刷新到的视频也有打不开的
