### ISSUE TITLE
我的收藏视频无法获取

### ISSUE THREAD

**Issue by rssau** [xiaoyaocz/biliuwp-lite#84]
系统版本：Windows 11 22000.466 应用版本：4.3.5.0
追番和追剧都没问题，就视频部分显示为空，提示“出现了一个未处理错误”
![屏幕截图 2022-01-21 155206](https://user-images.githubusercontent.com/50181645/150487912-209fb0dd-d119-4e43-abbc-3c856fff9bd4.jpg)

**Comment by ZzzzzzzSkyward** [comment]
更新到4.3.6.0版仍然存在该问题：`2022-03-09 11:18:04.4503|ERROR|BiliLite.Helpers.LogHelper|2|Object reference not set to an instance of an object.|Object reference not set to an instance of an object.    at BiliLite.Modules.MyFollowVideoVM.<LoadFavorite>d__27.MoveNext() + 0x418`

**Comment by ZzzzzzzSkyward** [comment]
> 更新到4.3.6.0版仍然存在该问题，系统为windows 10 x64 1809 17763.2565：`2022-03-09 11:18:04.4503|ERROR|BiliLite.Helpers.LogHelper|2|Object reference not set to an instance of an object.|Object reference not set to an instance of an object. at BiliLite.Modules.MyFollowVideoVM.<LoadFavorite>d__27.MoveNext() + 0x418`

4.3.7.0版已解决我的问题。

**Comment by rssau** [comment]
4.3.7.0 已解决，感谢！
